In [2]:
print('hello')

hello


In [4]:
pip install sklearn

Note: you may need to restart the kernel to use updated packages.


In [7]:
import numpy as np # alias (축약어)

In [8]:
a = [1,2,3]

b = np.array(a)

In [10]:
print(type(a))
print(type(b))

<class 'list'>
<class 'numpy.ndarray'>


In [13]:
array1 = b.copy()
array2 = np.array([4,5,6])
print('array1 type:' , type(array1))
print(array1)
print(array2)

array1 type: <class 'numpy.ndarray'>
[1 2 3]
[4 5 6]


In [15]:
array2d = np.array([[1,2,3],
                  [11,22,33]])
print('array2d type:' , type(array2d))
print(array2d)
print('array2d의 형태:', array2d.shape)
print('array2d는 {0}차원'.format(array2d.ndim))

array2d type: <class 'numpy.ndarray'>
[[ 1  2  3]
 [11 22 33]]
array2d의 형태: (2, 3)
array2d는 2차원


In [16]:
sq_array = np.arange(10)
sq_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])