# 행렬의 정렬 -sort()와 argsort()

In [7]:
import numpy as np

In [2]:
org_array = np.array([3, 1, 9, 5])
print('원본 행렬', org_array)

원본 행렬 [3 1 9 5]


In [4]:
# np.sort()로 정렬 (원본 불변)
sort_array1 = np.sort(org_array)
print('np.sort()호출후 반환된 정렬행렬', sort_array1)
print('np.sort()호출 후 반환된 원본행렬', org_array)

np.sort()호출후 반환된 정렬행렬 [1 3 5 9]
np.sort()호출 후 반환된 원본행렬 [3 1 9 5]


In [5]:
# np.sort()로 정렬 (원본 변함)
sort_array1 = org_array.sort()
print('sort() 만 적용후 반환된 정렬행렬', sort_array1)
print('sort() 만 적용후 반환된 원본행렬', org_array)

sort() 만 적용후 반환된 정렬행렬 None
sort() 만 적용후 반환된 원본행렬 [1 3 5 9]


In [ ]:
# 내림차순 정렬 => [:: -1]

In [11]:
np.sort(org_array)[:: -1]

array([9, 5, 3, 1])

In [ ]:
# axis 에 따른 정렬

In [17]:
array2d = np.array([[8,12],
                   [7,1]])
sort_array2d_ax0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_ax0)

sort_array2d_ax1 = np.sort(array2d, axis=1)
print('컬럼 방향으로 정렬:\n', sort_array2d_ax1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


# argsort() 함수 : 정렬된 행렬의 인덱스 변환

In [18]:
org_array = np.array([3,1,9,5]) # --> 1 3 9 5
                   #  0 1 2 3   #     1 0 3 2
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 후 원본행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 후 원본행렬의 인덱스: [1 0 3 2]


## 행렬의 내적 => 행렬의 곱

In [19]:
A = np.array([[1, 2, 3],
             [4, 5, 6]])

B = np.array([[7, 8],
             [9, 10],
             [11, 12]
             ])

np.dot(A, B)

array([[ 58,  64],
       [139, 154]])

### 전치행렬(Transpose)

In [21]:
A = np.array([[1,2],
             [3,4]])

transpose_A = np.transpose(A)
transpose_A

B = np.array([[1,2],
             [3,4],
             [5,6]])

transpose_B = np.transpose(B)
transpose_B


array([[1, 3, 5],
       [2, 4, 6]])

# Pandas - index

In [22]:
data = {'Name':['Chulmin','Eunkyoung','Jiwoong','Soobeom'],
        'Year':[2011,2016,2015,2015],
        'Gender':['Male','Female','Male','Male'],
        }

In [23]:
import pandas as pd

In [26]:
data_df = pd.DataFrame(data, index = ['one', 'two', 'three', 'four'])
data_df

Name  Year  Gender
one      Chulmin  2011    Male
two    Eunkyoung  2016  Female
three    Jiwoong  2015    Male
four     Soobeom  2015    Male

In [27]:
# 인덱싱 시작
# 1. 컬럼명

In [32]:
data_df['Name']

one        Chulmin
two      Eunkyoung
three      Jiwoong
four       Soobeom
Name: Name, dtype: object

In [ ]:
# 인덱싱 시작
# 1-1 행은 슬라이싱으로만

In [35]:
data_df[0:3]

Name  Year  Gender
one      Chulmin  2011    Male
two    Eunkyoung  2016  Female
three    Jiwoong  2015    Male

In [ ]:
# 단일값을 불러오기
# 1. iloc(Positional-위치)
# 2. loc(Label::명칭)

In [46]:
data_df.loc['three','Name'] # loc

data_df.iloc[2,0] # iloc

'Jiwoong'

In [53]:
# 연습
print(data_df.iloc[0:2,0:2])
print(data_df.iloc[0:2,[0,1]])
print(data_df.loc['one':'two','Name':'Year'])

          Name  Year
one    Chulmin  2011
two  Eunkyoung  2016
          Name  Year
one    Chulmin  2011
two  Eunkyoung  2016
          Name  Year
one    Chulmin  2011
two  Eunkyoung  2016


In [54]:
data_df['Year']

one      2011
two      2016
three    2015
four     2015
Name: Year, dtype: int64

In [55]:
data_df.Year>2014

one      False
two       True
three     True
four      True
Name: Year, dtype: bool

In [58]:
data_df.loc[data_df['Year']>2014][:2]

Name  Year  Gender
two    Eunkyoung  2016  Female
three    Jiwoong  2015    Male

In [69]:
## titanic data index
titan_df = pd.read_csv('C:/Users/송재원/Desktop/jwsong/23-01-30/titanic/train.csv')
titan_df

### 인덱스 객체 추출
Indexes = titan_df.index
print(Indexes)


### 인덱스 객체를 실제 값 array 로 변환
print('Index 객체 array값:\n', Indexes.values[:5])

RangeIndex(start=0, stop=891, step=1)
Index 객체 array값:
 [0 1 2 3 4]


In [71]:
print(type(Indexes.values))
print(Indexes.values.shape)

<class 'numpy.ndarray'>
(891,)


In [76]:
# 단 번에 인덱스 값 변환 x
Indexes[0]=1000

# 바꾸기 위해선 Index.values를 하고 변화한 값을 다시 pd.DataFrame(index=Index.values) 이렇게 바꿔야함

TypeError: Index does not support mutable operations