In [73]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder


In [ ]:
# 데이터 불러오고 필요없는 컬럼 드랍시키고 원하는값 인코딩 후 의사결정나무로 fetures, target => Train, test로 학습시킨후 accuracy_score

In [41]:
st_df = pd.read_csv('C:/Users/TECH2_25/TIL/Pandas/23-02-09/st_default.csv')
st_df

Unnamed: 0 default student      balance       income
0              1      No      No   729.526495  44361.62507
1              2      No     Yes   817.180407  12106.13470
2              3      No      No  1073.549164  31767.13895
3              4      No      No   529.250605  35704.49394
4              5      No      No   785.655883  38463.49588
...          ...     ...     ...          ...          ...
9995        9996      No      No   711.555020  52992.37891
9996        9997      No      No   757.962918  19660.72177
9997        9998      No      No   845.411989  58636.15698
9998        9999      No      No  1569.009053  36669.11236
9999       10000      No     Yes   200.922183  16862.95232

[10000 rows x 5 columns]

In [62]:
st_bal = st_df.balance

In [80]:
encoder = LabelEncoder()
encoder.fit(st_bal)
labels = encoder.transform(st_bal)

labels = labels.reshape(-1, 1)

oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)


원-핫 인코딩 데이터
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(10000, 9502)


In [81]:
pd.get_dummies(st_bal)

0.000000     0.023816     0.445757     1.611176     1.674026     \
0               0            0            0            0            0   
1               0            0            0            0            0   
2               0            0            0            0            0   
3               0            0            0            0            0   
4               0            0            0            0            0   
...           ...          ...          ...          ...          ...   
9995            0            0            0            0            0   
9996            0            0            0            0            0   
9997            0            0            0            0            0   
9998            0            0            0            0            0   
9999            0            0            0            0            0   

      1.976692     1.980734     2.287611     2.788920     2.843015     ...  \
0               0            0            0            0            0  ...   
1               0            0            0            0            0  ...   
2               0            0            0            0            0  ...   
3               0            0            0            0            0  ...   
4               0            0            0            0            0  ...   
...           ...          ...          ...          ...          ...  ...   
9995            0            0            0            0            0  ...   
9996            0            0            0            0            0  ...   
9997            0            0            0            0            0  ...   
9998            0            0            0            0            0  ...   
9999            0            0            0            0            0  ...   

      2387.314867  2388.174009  2391.007739  2413.319449  2415.316994  \
0               0            0            0            0            0   
1               0            0            0            0            0   
2               0            0            0            0            0   
3               0            0            0            0            0   
4               0            0            0            0            0   
...           ...          ...          ...          ...          ...   
9995            0            0            0            0            0   
9996            0            0            0            0            0   
9997            0            0            0            0            0   
9998            0            0            0            0            0   
9999            0            0            0            0            0   

      2461.506979  2499.016750  2502.684931  2578.469022  2654.322576  
0               0            0            0            0            0  
1               0            0            0            0            0  
2               0            0            0            0            0  
3               0            0            0            0            0  
4               0            0            0            0            0  
...           ...          ...          ...          ...          ...  
9995            0            0            0            0            0  
9996            0            0            0            0            0  
9997            0            0            0            0            0  
9998            0            0            0            0            0  
9999            0            0            0            0            0  

[10000 rows x 9502 columns]